### ISSUE TITLE
Update to use later/latest version of YUICompressor.NET

### ISSUE THREAD

**Issue by dove** [buunguyen/combres#22]
There have been improvements made to YUICompressor.NET and it boasts to almost match the Java version with the latest release.  

Taking a look at Combres code there would be some implications.  I'd have a go at making those changes but would like to get some feel on at least the first of the considerations below

1. Remove strong naming as YUICompressor.NET did so after version 1.7.   This would also make future upgrades much easier (without having to compile YUI each time).  There seems to be a twitter consensus that strong naming is losing favour, note a question from YUICompressor author: http://stackoverflow.com/questions/19215186/should-i-strongname-strong-sign-an-oss-dll 

2. The Compressor calls have been changed from being constructor passed to property setting.  Not major but the Css compressor no longer has a ColumnWidth property and now has a LineBreakPosition property.  Is this note worthy?  Should something be done with it?

3. Some configuration changes might have to be made for this as well, have not taken the debugging any further until I hear back.

**Comment by buunguyen** [comment]
I've pushed 2.3.0.4 which supports latest version of YUICompressor.
