### ISSUE TITLE
Update library dependencies

### ISSUE THREAD

**Issue by VAllens** [buunguyen/combres#37]
Local of Google Closure Compiler support.
Use to the IKVM.
Compile compiler.jar for compiler.dll
JDK is no longer required.
Updated Use dotLess 1.4.1.0, AjaxMin 5.11.5295.12309 and Log4Net 2.0.3
Link:https://github.com/vallens/combres

**Comment by buunguyen** [comment]
Combres 2.3.0.4 is just released and built with new libs.
