### ISSUE TITLE
Combres can not minify AngularJs

### ISSUE THREAD

**Issue by anhtata** [buunguyen/combres#39]
Hi Buu, 

I tried to use combres to compress AngularJs but it didn't work. Do you have any way to move all AngularJs files into one file. My project is working with ASP.NET 2, MVC.NET 2 and Combres 2.2

It's great if you have any solution!

Thanks in advanced!

**Comment by buunguyen** [comment]
What's the error you have? Generally, just populate combres.xml with all the necessary scripts in the right order and it should work.

**Comment by anhtata** [comment]
Yes I put them in the right order and it works well if defaultDebugEnabled="true"
If i change defaultDebugEnabled="false" then it displays Uncaught ReferenceError: $ is not defined
You can see at http://i.imgur.com/kobwyvp.png

**Comment by mrunalbrahmbhatt** [comment]
Try to change minifier. Like yui to ms ajax

**Comment by anhtata** [comment]
Thanks Buu very much, Now It worked well. 
I must fixed A Note on Minification of AgularJs at  https://docs.angularjs.org/tutorial/step_05 (follow guide form https://scotch.io/tutorials/declaring-angularjs-modules-for-minification)
and change minifier to msajax

**Comment by mrunalbrahmbhatt** [comment]
I had similar issues with Google clouser

Mrunal

**Comment by buunguyen** [comment]
Ah, the notorious AngularJS DI minification problem. Using array declaration DI syntax should fix it, I don't think it's necessary to switch the minifier although it also depends on your code.
