### ISSUE TITLE
Configs for YuiCssMinifier and YuiJSMinifier incorrect and cause exceptions

### ISSUE THREAD

**Issue by AdrianLogan** [buunguyen/combres#41]
In combres_full_with_annotation the options for the YUI minifiers are incorrect. This causes an exception if you try to use any of the YUI minifiers with the incorrect settings

    <minifier name="yui" type="Combres.Minifiers.YuiCssMinifier, Combres">
      <param name="CssCompressionType" type="string" value="StockYuiCompressor" />
      <param name="RemoveComments" type="bool" value="true" />
      <param name="ColumnWidth" type="int" value="-1" />
    </minifier>
   ---> CssCompressionType is not supported in YuiCssMinifier so needs to be removed
          ColumnWidth is also not supported.
         LineBreakPosition  is supported by not listed

    <minifier name="yui" type="Combres.Minifiers.YuiJSMinifier, Combres">
      <param name="IsVerboseLogging" type="bool" value="false" />
      <param name="IsObfuscateJavascript" type="bool" value="true" />
      <param name="PreserveAllSemicolons" type="bool" value="false" />
      <param name="DisableOptimizations" type="bool" value="false" />
      <param name="LineBreakPosition" type="int" value="-1" />
    </minifier>
  ---> IsObfuscateJavascript must be ObfuscateJavascript.
        There is also a IgnoreEval  property in YuiJSMinifier that is not described in the annotated xml

**Comment by buunguyen** [comment]
That's the old documentation. Version 2.3.x should have addressed that. https://github.com/buunguyen/combres/blob/master/Build%2Fcombres%2Fcontent%2FApp_Data%2Fcombres_full_with_annotation.xml
