### ISSUE TITLE
CombresHandler.ProcessRequest throwing ArgumentException with no discernible pattern.

### ISSUE THREAD

**Issue by AlphaWhelp** [buunguyen/combres#43]
The exact message of the Exception as viewable in the event handler is Combres.CombresHandler.ProcessRequest failed with System.ArgumentException: Requested value 'CrunchAll' was not found.

I, unfortunately, have very little information other than that.  It does not seem to have any discernible impact on the functionality of the website, but it is happening regardless.

The problem seems to be related to TypeExtensions.cs

![combres](https://cloud.githubusercontent.com/assets/13671707/9261583/e814b188-41dc-11e5-8c73-b6981b52c0fe.PNG)

**Comment by buunguyen** [comment]
CrunchAll is possible value of the enum LocalRenaming in MSAjaxJSMinifier. 

Which version of Combres and MSAjaxMin you have?

**Comment by AlphaWhelp** [comment]
I am not sure how to check what version I have.  It was added to the project in July of 2012 and has barely been touched.

Thanks.

**Comment by mrunalbrahmbhatt** [comment]
Check Dll property and then details.

**Comment by AlphaWhelp** [comment]
It is version 2.1.0.0

**Comment by buunguyen** [comment]
I remember that version got compiled with a version of MS Ajax Min that doesn't have LocalRenaming.CrunchAll option. So either upgrade Combres or modify combres.xml to get rid of that option. For the list of available options, check out MS Ajax Min documentation matching the version being used.

**Comment by AlphaWhelp** [comment]
Does this version allow for any LocalRenaming options that I can change in the XML and just not CrunchAll, or should I delete the LocalRenaming option altogether?

**Comment by buunguyen** [comment]
idk, please check the documentation of MS Ajax Min.
