### ISSUE TITLE
dotLess strictMath mode not configurable

### ISSUE THREAD

**Issue by oguzhankahyaoglu** [buunguyen/combres#44]
dotless has a lot of configurable property but as far as i see, u implemented dotless support in filters (Commented code was yours):

        //private static readonly DotlessConfiguration Config = new DotlessConfiguration
        //{
        //    CacheEnabled = false,
        //    MinifyOutput = false
        //};

        private static readonly bool IsStrictMathEnabled = (ConfigurationManager.GetSection("dotless") as DotlessConfiguration).StrictMath;

        private static readonly DotlessConfiguration Config = new DotlessConfiguration
        {
            CacheEnabled = false,
            MinifyOutput = false,
            StrictMath = IsStrictMathEnabled
        };

You should have implemented a way to configure it. Strict math is a key feature, css syntax is improving and there is no way to use "calc" support without it. So, i had to enable it by modifying your code. 

Thanks for improvements.

**Comment by buunguyen** [comment]
Would you mind submitting a PR for this?

**Comment by oguzhankahyaoglu** [comment]
you mean public reason? what is pr?

if you need a reason, it is your thought. i can go on with modified source code.

**Comment by buunguyen** [comment]
Sorry, I meant a pull request.

**Comment by oguzhankahyaoglu** [comment]
This is just a suggestion for you. Implementing or not is your decision because I dont have coherent knowledge about your project. So, i cannot take responsibility for that. This is just an idea.

I solved my problem just adding 2 lines to your source code. Further enhancements would be your decision.

**Comment by buunguyen** [comment]
Fantastic, this is exactly how open-source is supposed to work!
