### ISSUE TITLE
Nuget update

### ISSUE THREAD

**Issue by karczk** [buunguyen/combres#45]
Hi, is there any change for packages update like one year ago? New combres nuget with latest libraries would help in maintaining older projects.

**combres.log4net.nuspec**

from 
```
<dependency id="WebActivatorEx" version="[2.0.6]" />
<dependency id="dotless" version="[1.4.1.0]" />
```
to 
```
<dependency id="WebActivatorEx" version="2.1.0" />
<dependency id="dotless" version="1.5.2.0" />
```

**combres.log4net.nuspec**

from
`<dependency id="log4net" version="[2.0.3]" />`

to
`<dependency id="log4net" version="2.0.5" />`

For now, any update is not possible because of version range: [X.X.X]. Any newer WebActivatorEx package is not valid. X.X.X version range (without the square brackets) would be the best.
https://docs.nuget.org/create/versioning

**Comment by buunguyen** [comment]
I'll accept PR.
